name: Bot Tu Dong Quet HTML

on:
  schedule:
    # 22:00 UTC là 5:00 sáng hôm sau tại Việt Nam
    - cron: '0 22 * * *' 
  workflow_dispatch:     # Nút bấm chạy thủ công ngay lập tức
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu Github
        uses: actions/checkout@v3

      - name: Cai dat Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cai thu vien can thiet
        run: pip install requests

      - name: Chay file Python
        env:
          MY_EMAIL_PASS: ${{ secrets.MY_EMAIL_PASS }}
        run: python baocao.py
