name: Kich Hoat Mat Than Thuc Don
on:
  schedule:
    # Chạy vào 00:45, 04:45, 08:45 giờ UTC Thứ 7 hàng tuần
    # Tương ứng 07:45, 11:45, 15:45 giờ Việt Nam (UTC+7)
    - cron: '45 0,4,8 * * 6'

jobs:
  trigger_push:
    runs-on: ubuntu-latest
    steps:
      - name: Truy cap link thuc don để kich hoat script
        run: |
          curl -s https://[ten-user-cua-ban].github.io/github_data/029-thuc-on-cho-oi-truong.html > /dev/null
