name: Tu_Dong_Quet_Ma_Tran
on:
  schedule:
    - cron: '45 0 * * *'  # Tự chạy lúc 07:45 sáng
    - cron: '45 4 * * *'  # Tự chạy lúc 11:45 trưa
    - cron: '45 8 * * *'  # Tự chạy lúc 15:45 chiều
    - cron: '45 12 * * *' # Tự chạy lúc 19:45 tối
jobs:
  chay_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Chạy mã Python
        run: |
          pip install requests
          python bot_ma_tran.py
