name: Kich Hoat Thuc Don Nguoi Linh
on:
  schedule:
    # 00:00, 04:00, 08:00 UTC là 07:00, 11:00, 15:00 VN
    - cron: '0 0,4,8 * * 0'
  workflow_dispatch:

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - name: Cai dat moi truong
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Kich hoat trang HTML
        run: |
          python -c "
          import time
          from playwright.sync_api import sync_playwright
          url = 'https://namnguyen7133-png.github.io/Dien_thoai/025-thuc-on-i-linh.html'
          with sync_playwright() as p:
              browser = p.chromium.launch(headless=True)
              page = browser.new_page()
              print(f'Dang mo: {url}')
              page.goto(url)
              time.sleep(20) # Đợi JavaScript trong HTML chạy xong
              browser.close()
          "
