name: Gui Thong Bao Thuc Don Thu 7
on:
  schedule:
    # 00:00, 04:00, 08:00 UTC là 07:00, 11:00, 15:00 giờ VN (Báo trước 1 tiếng)
    - cron: '0 0,4,8 * * 6'
  workflow_dispatch:

jobs:
  thuc_don:
    runs-on: ubuntu-latest
    steps:
      - name: Cai dat Playwright
        run: |
          pip install playwright
          playwright install chromium
      - name: Kich hoat thuc don
        run: |
          python -c "
          import time
          from playwright.sync_api import sync_playwright
          url = 'https://namnguyen7133-png.github.io/Dien_thoai/029-thuc-on-cho-oi-truong.html'
          with sync_playwright() as p:
              browser = p.chromium.launch(headless=True)
              page = browser.new_page()
              page.goto(url)
              time.sleep(15) # Đợi script gửi Pushbullet
              browser.close()
          "
